Typing annotations for VectorBus.__init__(...) are missing
hardbyte/python-can pull request #1084
Opened 2021-06-09 08:13 UTC by felixdivo

Implements #1082. Features:
- more complete docstring (parameters were missing)
- actual typing annotations
- more general type for `channel` and better parsing
- small doc formatting improvements

2021-06-12 20:41 UTC, zariiii9003 requested changes

2021-06-12 20:41 UTC, zariiii9003 commented on can/interfaces/vector/canlib.py
> +            Name of application in the hardware config.
```suggestion
            Name of application in Vector Hardware Configuration.
```

This is the name of the Vector tool.

2021-06-12 20:41 UTC, zariiii9003 commented on can/interfaces/vector/canlib.py
> +            If set, the app_name does not have to be previously defined in the Vector hardware
Same here

2021-06-13 08:03 UTC, felixdivo commented on can/interfaces/vector/canlib.py
> +            config.
```suggestion
            If set, the app_name does not have to be previously defined in Vector Hardware
            Configuration.
```

2021-06-14 10:54 UTC, felixdivo commented
@zariiii9003 Is it finished like this?

2021-06-15 07:22 UTC, zariiii9003 approved these changes

2021-06-15 07:25 UTC, merged