Add ETAS interface
hardbyte/python-can pull request #1144
Opened 2021-10-25 18:14 UTC by felixn

This patch adds support for ETAS CAN Interfaces, based on the ETAS BOA (Basic Open API)

It's ready from a functional point of view.
I'm not sure what else is required for merging - @felixdivo, what do you think?
I tried to follow the steps described in https://github.com/hardbyte/python-can/blob/develop/doc/development.rst#creating-a-new-interfacebackend as well as #1149

I've added a back2back test, which mostly passes - but it can obviously only run successfully if an actual hardware interface is available.
![b2b](https://user-images.githubusercontent.com/221502/140608229-c3f43b99-a9dd-435d-9f22-747c195790cd.PNG)
- test_timestamp_is_absolute fails because timestamps are HW timestamps relative to powerup, not relative to unix epoch. What's the expected behaviour?
- test_unique_message_instances fails because the API does not seem to allow creating multiple instances of one channel with differing settings regarding self-reception...

Are further tests, e.g. unit tests with mocked API/HW access, mandatory?

2021-11-11 15:42 UTC, felixdivo commented
Hey @felixn, Felix here. ^^

At first glance, your PR looks very good! Mandatory is working code and proper documentation, of which you seem to have included both (I can't test the code since I do not have the required hardware). Further tests are not required.

Regarding the `timestamp`: According to [the docs](https://python-can.readthedocs.io/en/develop/message.html#can.Message.timestamp), they are relative to "epoch in seconds". For example, the `pcan` interface also translates timestamps like [this](https://github.com/hardbyte/python-can/blob/develop/can/interfaces/pcan/pcan.py#L20). Maybe one could move that piece of code to `can/util.py` and you can use it too? Could you do that?

Regarding the last test case: It's totally fine to skip the test case if that is not supported, just add this to your test case class (you can of course change the description as you see fit):

```python
def test_unique_message_instances(self):
    self.skipTest("Creating the test environment with additional buses is not supported")
```

2021-11-11 16:08 UTC, felixdivo commented
If you choose to implement the suggested `timestamp` fix, you'd also need to [add a extension key to `setup.py`](https://github.com/hardbyte/python-can/blob/develop/setup.py#L35) and advice users to install the entire library with `pip install can[etas]` (or something like that).

2021-11-11 17:48 UTC, felixn commented
Hi Felix ;)
Thanks for the quick feedback!

I've made changes you suggested to make the timestamps relative to epoch.
Luckily, I didn't need the additional uptime library, since in this case the timestamps are relative to a hardware timer.

Ready to merge from my point of view!

2021-11-11 19:13 UTC, felixdivo requested changes
Okay, I went through your code line-by-line (except for `can/interfaces/etas/boa.py`).

This is a well-written contribution! Thank you!

The changes I mentioned are all rather small (I hope), except for the `errcheck` idea. What do you think?

By the way: A final review by @hardbyte is also required, only then this will be merged.

2021-11-11 19:13 UTC, felixdivo commented on can/interfaces/etas/__init__.py
> +        # if new_state == can.BusState.ACTIVE:
If there is a problem with the disabled code, one should probably add a brief comment on what's up.

2021-11-11 19:13 UTC, felixdivo commented on can/interfaces/etas/__init__.py
> +        nodes = []
```suggestion
        nodes: Dict[str, str] = []
```

2021-11-11 19:13 UTC, felixdivo commented on can/interfaces/etas/boa.py
> +CSI_CreateProtocolTree.restype = BOA_ResultCode
One could also add `CSI_CreateProtocolTree.errcheck = ...` to use [this](https://docs.python.org/3/library/ctypes.html#ctypes._FuncPtr.errcheck) (and similarly for the other methods). Just an idea, maybe it simplifies the bus class?

2021-11-14 15:23 UTC, felixn commented on can/interfaces/etas/__init__.py
> +        channel: Any,
:+1:

2021-11-14 15:23 UTC, felixn commented on can/interfaces/etas/__init__.py
> +            raise can.exceptions.CanInitializationError(
:+1:

2021-11-14 15:23 UTC, felixn commented on can/interfaces/etas/__init__.py
> +        # all timestamps are hardware timestamps relative to powerup
:+1:

2021-11-14 15:23 UTC, felixn commented on can/interfaces/etas/__init__.py
> +            t = OCI_Time(int(timeout * self.tickFrequency))
:+1:

2021-11-14 18:10 UTC, felixn commented
Thanks for the feedback @felixdivo - all valuable, I made the changes you requested.
@hardbyte - what do you think?

2021-11-14 22:30 UTC, felixdivo approved these changes
Nice!

2021-11-19 15:17 UTC, vincent-mailhol commented
@nbusser, thanks for the mention. Indeed, Philipp Ahrendt and myself also implemented all the bindings for the ETAS interfaces. However, I never implemented the mock-up test thus my pull request failed the auto checks. Since then, I moved to some other projects. I do not think I will go back on this one day. None the less, what we did was tested with a wide variety of ETAS hardware (including the virtual bus) to make sure to capture all the edge cases.
@felixn thanks for your work. I would really be happy to see the ETAS interface merged to python CAN. I also recommend you to have a look at what we did. We did our best to cover all the use cases such as the older API (BOA version 1.0.0 to 1.4.0), the bus errors (Error active, passive, bus off…). We also added an interface for the optional bit timing parameters (time segment, Synchronization Jump Width…)

2021-11-19 15:28 UTC, vincent-mailhol commented on doc/interfaces/etas.rst
> +Only Windows is supported.
I propose to rephrase this line as below:

Only Windows is supported by this interface. The Linux kernel v5.13 (and greater) natively supports ETAS ES581.4, ES582.1 and ES584.1 USB modules. To use these under Linux, please refer to :ref:`socketcan`.

2021-11-22 17:05 UTC, felixn commented
@vincent-mailhol & @nbusser :
Thanks for connecting the dots!
Still, I must say that this is a rather frustrating situation - discovering code in pull requests is next to impossible, and a lot of effort could have been saved...

I see several good ideas from your code that I could adopt - as you mentioned.
However, the code as it is right now is functional and a big improvement from "no support at all".
@hardbyte - are you ok with merging this as-is, and extending in a second step?
I can't justify spending the effort to extend the implementation for more use cases without some kind of assurance the code will be considered for merging.

2021-12-06 09:01 UTC, felixdivo commented
> @hardbyte - are you ok with merging this as-is, and extending in a second step?

I'm not him, but I'd say it's fine to merge it like this. However, improving the documentation with the small [suggestion](https://github.com/hardbyte/python-can/pull/1144#discussion_r753292233) by @vincent-mailhol would still be useful in this PR. Afterwards, I'd personally say it's ready to be merged.

2021-12-06 09:49 UTC, hardbyte commented
> > @hardbyte - are you ok with merging this as-is, and extending in a second step?
> 
> I'm not him, but I'd say it's fine to merge it like this. However, improving the documentation with the small [suggestion](https://github.com/hardbyte/python-can/pull/1144#discussion_r753292233) by @vincent-mailhol would still be useful in this PR. Afterwards, I'd personally say it's ready to be merged.

@felixn thanks for your contribution. I understand the frustration and uncertainty, I'm really disappointed when I see changes not make it in and also when efforts are duplicated. It's at least partly my fault for trying to stay across all core changes - despite the fact I haven't used CAN professionally in about 7 years(!)

I  try to ensure we only merge clear and maintainable code but I'm (obviously) not able to keep up. I plan to make a few tweaks over my Christmas break primarily to ensure things are more sustainable. Long story short, as long as a core contributor like @felixdivo approves a change it shouldn't need me.

2021-12-12 19:56 UTC, hardbyte approved these changes

2021-12-13 16:51 UTC, felixdivo commented
@felixn I just resolved the conflicts. If you address above [comment](https://github.com/hardbyte/python-can/pull/1144/#discussion_r753292233), we can merge this contribution and include it in the next major release that will be coming out soon.

2021-12-16 16:31 UTC, felixn commented
@hardbyte - thanks for the feedback! No worries, I completely understand. The time and motivation necessary for spare time open source projects is not always the same - at least, that's how it is for me.

@felixdivo - thanks for resolving the conflicts, and for proposing to include it in the next release. I made the suggested changes.
After that, I can spend some time on porting/including the additional functionality from @vincent-mailhol's PR.

2021-12-16 18:15 UTC, felixdivo approved these changes
I'm just gonna change this small thing :)

2021-12-16 18:15 UTC, felixdivo commented on doc/interfaces/etas.rst
> +Only Windows is supported by this interface. The Linux kernel v5.13 (and greater) natively supports ETAS ES581.4, ES582.1 and ES584.1 USB modules. To use these under Linux, please refer to :ref:socke
```suggestion
Only Windows is supported by this interface.
The Linux kernel v5.13 (and greater) natively supports ETAS ES581.4, ES582.1 and ES584.1 USB modules.
To use these under Linux, please refer to :ref:`socketcan`.
```

2021-12-16 22:59 UTC, merged