[IO][canutils]: add direction support
hardbyte/python-can pull request #1244
Opened 2022-01-28 17:15 UTC by jazi007

PR for https://github.com/hardbyte/python-can/issues/1243

2022-02-06 10:04 UTC, felixdivo commented on can/io/canutils.py
> +                eol = " T\n"
It's shorter and still well-readable:

```suggestion
            eol = " R\n" if msg.is_rx else " T\n"
```

2022-02-06 10:04 UTC, felixdivo commented on can/io/canutils.py
> +            framestr += "R%s" % (eol)
```suggestion
            framestr += f"R{eol}"
```

2022-02-06 10:04 UTC, felixdivo commented on can/io/canutils.py
> +            framestr += "%s%s" % (msg.data.hex().upper(), eol)
```suggestion
            framestr += f"{msg.data.hex().upper()}{eol}"
```

2022-02-06 10:12 UTC, felixdivo requested changes
Apart from the above, this looks good.

For reference: https://github.com/linux-can/can-utils/blob/master/asc2log.c#L185

2022-02-06 14:28 UTC, jazi007 commented on can/io/canutils.py
> +            if temp[-2:].lower() in [" r", " t"]:
Done

2022-02-06 14:28 UTC, jazi007 commented on can/io/canutils.py
> +                eol = " T\n"
Done

2022-02-06 14:28 UTC, jazi007 commented on can/io/canutils.py
> +            framestr += "R%s" % (eol)
Done

2022-02-06 14:28 UTC, jazi007 commented on can/io/canutils.py
> +            framestr += "%s%s" % (msg.data.hex().upper(), eol)
Done

2022-02-06 15:09 UTC, felixdivo approved these changes

2022-03-01 18:00 UTC, felixdivo commented
As [mentioned in issue \#1217](https://github.com/hardbyte/python-can/pull/1217#issuecomment-1055706495): This can be merged now.

2022-03-01 18:15 UTC, merged