Convert setup.py to pyproject.toml
hardbyte/python-can pull request #1592
Opened 2023-05-12 18:33 UTC by Tbruno25

Closes #1563

2023-05-15 14:39 UTC, zariiii9003 requested changes

2023-05-15 14:39 UTC, zariiii9003 commented on pyproject.toml
> +[build-system]
This is usually at the top of the file

2023-05-15 14:39 UTC, zariiii9003 commented on .github/workflows/ci.yml
> +        pip install .[lint]
```suggestion
        pip install -e .[lint]
```

2023-05-15 14:39 UTC, zariiii9003 commented on .github/workflows/ci.yml
> +        pip install .[lint]
```suggestion
        pip install -e .[lint]
```

2023-05-15 14:39 UTC, zariiii9003 commented on .github/workflows/format-code.yml
> +        pip install .[lint]
```suggestion
        pip install -e .[lint]
```

2023-05-15 14:39 UTC, zariiii9003 commented on pyproject.toml
> +    "Programming Language :: Python :: 3.7",
the python versions could be sorted here 😄

2023-05-15 14:39 UTC, zariiii9003 commented on pyproject.toml
> +requires-python = ">=3.7, <=4.0"
```suggestion
requires-python = ">=3.7"
```

2023-05-15 14:39 UTC, zariiii9003 commented on pyproject.toml
> +requires = ["packaging", "setuptools >= 40.8", "wheel"]
`packaging` is a runtime dependency, not a build dependency. `setuptools` must be >=61 for pyproject.toml support, but i would just set the latest version as the new minimum. `wheel` is not necessary anymore.

2023-05-16 16:17 UTC, Tbruno25 commented
Updated to include the suggestions! :rocket:

2023-05-16 16:57 UTC, zariiii9003 approved these changes
Looks good, thanks!

2023-05-16 16:57 UTC, merged