Upate Changelog for Release v.4.3.0
hardbyte/python-can pull request #1680
Opened 2023-10-14 16:48 UTC by lumagi

@zariiii9003 I tried to remove bugfixes already included in v4.2.2. Please also check if you agree with the sorting and categorization of entries.

2023-10-14 18:58 UTC, zariiii9003 requested changes

2023-10-14 18:58 UTC, zariiii9003 commented on CHANGELOG.md
> +* Send HighPriority Message to flush VectorBus Tx buffer (#1636)
```suggestion
* Vector: Send HighPriority Message to flush Tx buffer (#1636)
```

2023-10-14 18:58 UTC, zariiii9003 commented on CHANGELOG.md
> +* Vector: Skip the `can_op_mode check` if the device reports `can_op_mode=0` (#1678)
I'd move this to bug fixes.

2023-10-14 18:58 UTC, zariiii9003 commented on CHANGELOG.md
> +* PCAN: remove Windows registry check (#1672)
```suggestion
* PCAN: remove Windows registry check to fix 32bit compatibility (#1672)
```

2023-10-14 18:58 UTC, zariiii9003 commented on CHANGELOG.md
> +* Distinguish Text/Binary-IO for Reader/Writer classes. (#1585)
This is just a type annotation issue, i'd move this to miscellaneous

2023-10-14 18:58 UTC, zariiii9003 commented on CHANGELOG.md
> +* Add auto-modifying cyclic tasks (#703)
```suggestion
* Add `modifier_callback` parameter to `BusABC.send_periodic` for auto-modifying cyclic tasks (#703)
```

Add an "API" sub section to "Features", there are a few points here, which i'd move to API

2023-10-14 18:58 UTC, zariiii9003 commented on CHANGELOG.md
> +* Relax BitTiming & BitTimingFd Validation (#1618)
```suggestion
* Add optional `strict` parameter to relax BitTiming & BitTimingFd Validation (#1618)
```
Move to API

2023-10-14 18:58 UTC, zariiii9003 commented on CHANGELOG.md
> +* Catch `pywintypes.error` in broadcast manager (#1659)
Move to bug fixes

2023-10-14 18:58 UTC, zariiii9003 commented on CHANGELOG.md
> +* Do not stop notifier if exception was handled (#1645)
This one could be a breaking change 🤔

2023-10-14 18:58 UTC, zariiii9003 commented on CHANGELOG.md
> +* Add `BitTiming.iterate_from_sample_point` static methods (#1671)
Move to API

2023-10-14 18:58 UTC, zariiii9003 commented on CHANGELOG.md
> +* Support version string of older PCAN basic API (#1644)
```suggestion
* PCAN: Support version string of older PCAN basic API (#1644)
```

2023-10-14 18:58 UTC, zariiii9003 commented on CHANGELOG.md
> +* Optimize PCAN send performance (#1640)
```suggestion
* PCAN: Optimize send performance (#1640)
```

2023-10-14 18:58 UTC, zariiii9003 commented on CHANGELOG.md
> +* Add `protocol` property to BusABC to determine active CAN Protocol (#1532)
Move to API

2023-10-14 18:58 UTC, zariiii9003 commented on CHANGELOG.md
> +* Fix Vector channel detection (#1634)
```suggestion
* Vector: channel detection fails, if there is an active flexray channel  (#1634)
```

2023-10-14 18:58 UTC, zariiii9003 commented on CHANGELOG.md
> +* Fix PCAN timestamp (#1651)
```suggestion
* PCAN: Fix timestamp offset due to timezone (#1651)
```

2023-10-14 18:58 UTC, zariiii9003 commented on CHANGELOG.md
> +* We do not need to account for drift when we `USE_WINDOWS_EVENTS` (#1666)
Move to miscellaneous, it's not really a bug.

2023-10-14 19:23 UTC, lumagi commented
Sorry for the many commits, I probably could have batched your change request.

2023-10-14 22:54 UTC, zariiii9003 commented
You missed a few comments 😄

2023-10-16 08:37 UTC, lumagi commented on CHANGELOG.md
> +* Vector: Skip the `can_op_mode check` if the device reports `can_op_mode=0` (#1678)
You mean line 35 only, right?

2023-10-16 08:41 UTC, lumagi commented on CHANGELOG.md
> +* Relax BitTiming & BitTimingFd Validation (#1618)
I think this one got lost.

2023-10-16 08:41 UTC, lumagi commented on CHANGELOG.md
> +* Catch `pywintypes.error` in broadcast manager (#1659)
And this one

2023-10-16 08:48 UTC, lumagi commented
You're right, I think Github was trying to be nice by compacting the view there.

2023-10-16 09:23 UTC, zariiii9003 commented on CHANGELOG.md
> +* Vector: Skip the `can_op_mode check` if the device reports `can_op_mode=0` (#1678)
Yes, line 35

2023-10-16 20:30 UTC, zariiii9003 commented on CHANGELOG.md
> +* We do not need to account for drift when we `USE_WINDOWS_EVENTS` (#1666)
```suggestion
* We do not need to account for drift when we `USE_WINDOWS_EVENTS` (#1666, #1679)
```

2023-10-16 21:15 UTC, zariiii9003 commented
@lumagi Can you add #1607 and bump the version to `4.3.0rc0`?

2023-10-17 09:46 UTC, zariiii9003 approved these changes

2023-10-17 09:47 UTC, merged

2023-10-17 10:19 UTC, zariiii9003 commented
@lumagi It's released: https://pypi.org/project/python-can/4.3.0rc0/
Thank you! 😃

2023-10-17 11:54 UTC, lumagi commented
Great, thanks for pushing the release!

2023-11-01 18:06 UTC, zariiii9003 commented
@hardbyte Would you like to release 4.3? Two weeks passed and so far no complaints about the pre-release...

2023-11-01 19:01 UTC, hardbyte commented
Let's do it!

2023-11-09 12:56 UTC, lumagi commented
> @hardbyte Would you like to release 4.3? Two weeks passed and so far no complaints about the pre-release...

Can I support here?

2023-11-10 04:41 UTC, hardbyte commented
That would be great thanks - I'll open a PR bumping the version but feel free to check and edit the changelog.